# Top-level configuration
name = "tom-and-barbara-anniversary"
main = "src/index.js"
compatibility_date = "2024-07-03"

# This tells Wrangler to serve static assets from the 'public' directory.
[[site]]
bucket = "./public"
